import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import { Mina, Nunito_Sans, Sora } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import "./globals.css";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700"],
});
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${sora.variable}`}>
        <video
          className="backgroundVideo"
          src="/images/herovideo.mp4"
          autoPlay
          muted
          loop
          playsInline
        />
        <TanStackProvider>
          <AuthProvider>
            <div className="videoWrapper">
        
        <div className="videoOverlay"/>
        <div className="videoContent">
          <Header />
          <Hero />
        </div>
      </div>
            <main>{children}</main>
            <Footer />
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
