import type { Metadata } from "next";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import { Nunito_Sans, Sora } from "next/font/google";
import Footer from "@/components/Footer/Footer";


const nunito = Nunito_Sans({
  subsets: ["latin"],
  variable: "--second-family",
  weight: ["400", "500", "600", "700"]
});
const sora = Sora({
  subsets: ["latin"],
  variable: "--first-family",
   weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${sora.variable}`}>
        <Header />
        {children}
        <Footer />

      </body>
    </html>
  );
}
